# DBT Project Configuration for Emergency Management Pipeline
name: 'emergency_management'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'emergency_management'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configuration
models:
  emergency_management:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +tags: ["staging", "emergency_data"]
    
    marts:
      +materialized: table
      +tags: ["marts", "emergency_data"]
      
    metrics:
      +materialized: table
      +tags: ["metrics", "emergency_data"]

# Snapshot configuration
snapshots:
  emergency_management:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Test configuration
tests:
  +store_failures: true
  +schema: test_failures

# Seed configuration  
seeds:
  emergency_management:
    +schema: reference_data

# Variables for federal compliance
vars:
  # Data retention periods (in days)
  disaster_data_retention: 2555  # 7 years for federal compliance
  weather_data_retention: 1095   # 3 years
  audit_log_retention: 2555      # 7 years
  
  # Data classification levels
  data_classification:
    public: "PUBLIC"
    internal: "INTERNAL" 
    restricted: "RESTRICTED"
    confidential: "CONFIDENTIAL"
  
  # Federal compliance flags
  fedramp_compliance: true
  dora_compliance: true
  audit_logging: true
  
  # Processing parameters
  batch_size: 10000
  max_parallel_jobs: 4