# Federal Compliance Configuration
# FedRAMP, DORA, FISMA, and other federal compliance requirements

# Compliance Frameworks
frameworks:
  fedramp:
    name: "Federal Risk and Authorization Management Program"
    level: "Moderate"  # Low, Moderate, High
    enabled: true
    requirements:
      - encryption_at_rest
      - encryption_in_transit
      - access_controls
      - audit_logging
      - incident_response
      - continuous_monitoring
      
  dora:
    name: "Digital Operational Resilience Act"
    enabled: true
    requirements:
      - operational_resilience
      - risk_management
      - incident_reporting
      - third_party_monitoring
      - testing_procedures
      
  fisma:
    name: "Federal Information Security Management Act"
    enabled: true
    requirements:
      - information_security_program
      - risk_assessments
      - security_controls
      - contingency_planning
      - awareness_training

# Data Classification Levels
data_classification:
  levels:
    public:
      label: "PUBLIC"
      description: "Information approved for public release"
      encryption_required: false
      access_restrictions: none
      retention_years: 7
      
    internal:
      label: "INTERNAL"
      description: "Internal use within organization"
      encryption_required: true
      access_restrictions: organization_members
      retention_years: 7
      
    restricted:
      label: "RESTRICTED"
      description: "Sensitive information requiring special handling"
      encryption_required: true
      access_restrictions: authorized_personnel
      retention_years: 7
      field_level_encryption: true
      
    confidential:
      label: "CONFIDENTIAL"
      description: "Highly sensitive information"
      encryption_required: true
      access_restrictions: cleared_personnel
      retention_years: 10
      field_level_encryption: true
      additional_controls: true

# Access Control Requirements
access_control:
  authentication:
    multi_factor_required: true
    session_timeout_minutes: 120
    max_concurrent_sessions: 3
    password_policy:
      min_length: 14
      complexity_required: true
      expiration_days: 90
      history_count: 12
      
  authorization:
    role_based_access: true
    principle_of_least_privilege: true
    segregation_of_duties: true
    regular_access_reviews: true
    
  tenant_isolation:
    database_separation: true
    network_segmentation: true
    encryption_key_separation: true
    audit_log_separation: true

# Audit and Logging Requirements
audit_logging:
  retention_years: 7
  real_time_monitoring: true
  tamper_protection: true
  
  events_to_log:
    - user_authentication
    - data_access
    - data_modification
    - privilege_escalation
    - system_configuration_changes
    - security_events
    - error_conditions
    
  log_fields:
    required:
      - timestamp
      - user_id
      - source_ip
      - action_performed
      - resource_accessed
      - outcome
      - tenant_id
      
    optional:
      - session_id
      - user_agent
      - additional_context
      
  log_formats:
    structured: true
    json_format: true
    siem_compatible: true

# Encryption Requirements
encryption:
  at_rest:
    enabled: true
    algorithm: "AES-256"
    key_management: "FIPS 140-2 Level 2"
    key_rotation_days: 90
    
  in_transit:
    enabled: true
    tls_version: "1.3"
    cipher_suites: "FIPS approved"
    certificate_validation: true
    
  field_level:
    pii_fields: true
    sensitive_data: true
    per_tenant_keys: true
    algorithm: "AES-256-GCM"

# Incident Response
incident_response:
  plan_documented: true
  team_identified: true
  contact_procedures: documented
  
  incident_types:
    security_breach:
      severity: critical
      response_time_minutes: 15
      notification_required: true
      
    data_breach:
      severity: critical
      response_time_minutes: 30
      notification_required: true
      regulatory_reporting: true
      
    system_outage:
      severity: high
      response_time_minutes: 60
      notification_required: false
      
  notification_requirements:
    internal:
      security_team: immediate
      management: "within 2 hours"
      affected_users: "within 4 hours"
      
    external:
      customers: "within 24 hours"
      regulators: "within 72 hours"
      law_enforcement: "as required"

# Business Continuity
business_continuity:
  backup_requirements:
    frequency: daily
    retention_days: 2555  # 7 years
    testing_frequency: monthly
    offsite_storage: true
    
  disaster_recovery:
    rto_hours: 4  # Recovery Time Objective
    rpo_hours: 1  # Recovery Point Objective
    testing_frequency: quarterly
    documented_procedures: true
    
  high_availability:
    uptime_target: 99.9
    redundancy: multi_zone
    failover_automatic: true

# Risk Management
risk_management:
  risk_assessments:
    frequency: annually
    methodology: "NIST RMF"
    documented_results: true
    
  vulnerability_management:
    scanning_frequency: weekly
    patch_timeline_days: 30
    critical_patch_hours: 72
    
  third_party_risk:
    vendor_assessments: required
    contract_requirements: security_clauses
    monitoring: continuous

# Privacy Protection
privacy:
  frameworks:
    - GDPR
    - CCPA
    - Privacy_Act_1974
    
  pii_handling:
    identification: automatic
    classification: required
    encryption: field_level
    access_logging: detailed
    
  data_subject_rights:
    access_requests: supported
    rectification: supported
    erasure: supported
    portability: supported
    
  consent_management:
    granular_consent: true
    withdrawal_mechanism: true
    consent_records: maintained

# Monitoring and Continuous Compliance
monitoring:
  security_metrics:
    collection_frequency: real_time
    dashboard_updates: hourly
    reporting_frequency: weekly
    
  compliance_checks:
    automated_scanning: daily
    manual_reviews: monthly
    compliance_reporting: quarterly
    
  alerting:
    security_events: immediate
    compliance_violations: immediate
    performance_degradation: "within 15 minutes"

# Documentation Requirements
documentation:
  policies_procedures:
    security_policy: required
    privacy_policy: required
    incident_response_plan: required
    business_continuity_plan: required
    
  technical_documentation:
    system_architecture: required
    data_flow_diagrams: required
    security_controls: required
    api_documentation: required
    
  training_materials:
    security_awareness: required
    compliance_training: required
    incident_response_training: required

# Compliance Validation
validation:
  internal_audits:
    frequency: quarterly
    scope: comprehensive
    reporting: management
    
  external_audits:
    frequency: annually
    auditor_requirements: certified
    frameworks: "FedRAMP, SOC 2"
    
  penetration_testing:
    frequency: annually
    scope: comprehensive
    remediation_timeline: 90_days
    
  vulnerability_assessments:
    frequency: monthly
    automated_tools: required
    manual_verification: quarterly

# Regulatory Reporting
reporting:
  required_reports:
    fisma_annual: true
    fedramp_continuous: true
    privacy_impact_assessments: true
    
  report_formats:
    structured_data: required
    narrative_sections: required
    supporting_evidence: required
    
  submission_timelines:
    monthly_metrics: "by 15th of following month"
    quarterly_reports: "within 30 days of quarter end"
    annual_assessments: "within 90 days of fiscal year end"

# Tenant-Specific Compliance
tenant_compliance:
  colorado_state:
    additional_frameworks:
      - Colorado_Privacy_Act
      - State_Records_Act
    data_residency: Colorado_preferred
    audit_frequency: quarterly
    
  federal_dhs:
    additional_frameworks:
      - CJIS_Security_Policy
      - ICD_503
    clearance_required: true
    enhanced_monitoring: true
    dedicated_resources: true
    
  local_government:
    additional_frameworks:
      - Local_Government_Records_Act
    simplified_compliance: true
    shared_resources: allowed

# Compliance Automation
automation:
  policy_enforcement:
    automated_controls: maximum
    manual_overrides: logged_and_approved
    
  compliance_monitoring:
    real_time_scanning: true
    automated_remediation: "where safe"
    alert_generation: immediate
    
  reporting:
    automated_generation: true
    human_review: required
    digital_signatures: true