# Emergency Management Data Sources Configuration
# Modular configuration for all emergency data sources

# Global source settings
global_settings:
  default_timeout_seconds: 30
  default_rate_limit_per_minute: 60
  default_retry_attempts: 3
  default_retry_delay_seconds: 1

# FEMA OpenFEMA API Configuration
fema:
  name: "FEMA OpenFEMA"
  description: "Federal Emergency Management Agency disaster declarations and assistance data"
  enabled: true
  
  api:
    base_url: "https://www.fema.gov/api/open/v2/"
    api_key_required: false
    api_key_env_var: "FEMA_API_KEY"
    rate_limit_per_minute: 60
    timeout_seconds: 30
    
  endpoints:
    disaster_declarations:
      path: "DisasterDeclarationsSummaries"
      description: "Disaster declarations and summaries"
      batch_size: 1000
      max_records: 10000
      
    public_assistance:
      path: "PublicAssistanceApplicants"
      description: "Public assistance applicant data"
      batch_size: 1000
      max_records: 5000
      
    hazard_mitigation:
      path: "HazardMitigationAssistance"
      description: "Hazard mitigation assistance projects"
      batch_size: 500
      max_records: 5000
  
  data_classification: "PUBLIC"
  update_frequency: "hourly"
  retention_days: 2555  # 7 years for federal compliance
  
  filters:
    default_state: null
    default_start_date: "30_days_ago"
    include_closed_disasters: true

# NOAA Weather API Configuration  
noaa:
  name: "NOAA Weather Service"
  description: "National Weather Service alerts, forecasts, and observations"
  enabled: true
  
  api:
    base_url: "https://api.weather.gov/"
    api_key_required: false
    contact_info_env_var: "NOAA_CONTACT_INFO"
    rate_limit_per_minute: 300  # Higher limit for weather data
    timeout_seconds: 20
    
  endpoints:
    active_alerts:
      path: "alerts/active"
      description: "Active weather alerts and warnings"
      batch_size: 500
      max_records: 2000
      
    forecast_zones:
      path: "zones/forecast"
      description: "Weather forecast zones"
      batch_size: 100
      max_records: 1000
      
    stations:
      path: "stations"
      description: "Weather observation stations"
      batch_size: 200
      max_records: 2000
      
    observations:
      path: "stations/{station_id}/observations"
      description: "Weather observations for specific station"
      batch_size: 100
      max_records: 500
  
  data_classification: "PUBLIC"
  update_frequency: "real_time"  # Every 5-15 minutes
  retention_days: 365
  
  filters:
    default_severity: null
    include_expired_alerts: false
    max_alert_age_hours: 24

# Colorado Agricultural Meteorological Network
coagmet:
  name: "CoAgMet"
  description: "Colorado Agricultural Meteorological Network weather station data"
  enabled: true
  
  api:
    base_url: "https://coagmet.colostate.edu/data_access/web_service/"
    api_key_required: false
    rate_limit_per_minute: 30  # Lower limit to be respectful
    timeout_seconds: 45
    
  endpoints:
    stations:
      path: "get_stations.php"
      description: "List of CoAgMet weather stations"
      batch_size: null
      max_records: 200
      
    station_data:
      path: "get_data.php"
      description: "Weather data for specific station"
      batch_size: 1000
      max_records: 5000
      parameters:
        format: "json"
        
    latest_readings:
      path: "get_latest.php"
      description: "Latest readings from all stations"
      batch_size: null
      max_records: 200
  
  data_classification: "PUBLIC"
  update_frequency: "hourly"
  retention_days: 1095  # 3 years for agricultural analysis
  
  filters:
    default_time_window_hours: 24
    include_quality_flags: true
    min_data_quality: "good"

# USDA Agricultural Data
usda:
  name: "USDA NASS"
  description: "United States Department of Agriculture National Agricultural Statistics Service"
  enabled: true
  
  api:
    base_url: "https://quickstats.nass.usda.gov/api/"
    api_key_required: true
    api_key_env_var: "USDA_API_KEY"
    rate_limit_per_minute: 30
    timeout_seconds: 60
    
  endpoints:
    crop_data:
      path: "api_GET/"
      description: "Crop production and yield data"
      batch_size: 1000
      max_records: 10000
      parameters:
        source_desc: "SURVEY"
        sector_desc: "CROPS"
        format: "JSON"
        
    livestock_data:
      path: "api_GET/"
      description: "Livestock inventory and production"
      batch_size: 1000
      max_records: 5000
      parameters:
        source_desc: "SURVEY"
        sector_desc: "ANIMALS & PRODUCTS"
        format: "JSON"
        
    disaster_assistance:
      path: "api_GET/"
      description: "Agricultural disaster assistance data"
      batch_size: 500
      max_records: 2000
      parameters:
        source_desc: "SURVEY"
        format: "JSON"
  
  data_classification: "PUBLIC"
  update_frequency: "daily"
  retention_days: 2555  # 7 years
  
  filters:
    default_year: "current"
    include_estimates: true
    statisticcat_desc: "AREA HARVESTED"

# Custom/External Source Template
custom_source_template:
  name: "Custom Source Template"
  description: "Template for adding new emergency data sources"
  enabled: false
  
  api:
    base_url: "https://api.example.com/"
    api_key_required: true
    api_key_env_var: "CUSTOM_API_KEY"
    rate_limit_per_minute: 60
    timeout_seconds: 30
    
  endpoints:
    main_data:
      path: "data"
      description: "Main data endpoint"
      batch_size: 1000
      max_records: 10000
      
  data_classification: "PUBLIC"
  update_frequency: "hourly"
  retention_days: 365
  
  # Custom authentication if needed
  authentication:
    type: "bearer_token"  # or "api_key", "oauth2", "basic_auth"
    header_name: "Authorization"
    
  # Custom data transformation
  transformation:
    date_fields: ["timestamp", "created_at"]
    numeric_fields: ["value", "count"]
    required_fields: ["id", "timestamp"]

# Source Groupings for Pipeline Management
source_groups:
  weather_sources:
    - noaa
    - coagmet
    description: "Weather and meteorological data sources"
    update_frequency: "real_time"
    
  disaster_sources:
    - fema
    description: "Disaster declaration and response data"
    update_frequency: "hourly"
    
  agricultural_sources:
    - coagmet
    - usda
    description: "Agricultural and farming data sources"
    update_frequency: "daily"
    
  all_public:
    - fema
    - noaa
    - coagmet
    - usda
    description: "All public emergency management data sources"

# Data Pipeline Configuration
pipeline_settings:
  # Microbatching for Flink
  microbatch_size: 100
  microbatch_interval_seconds: 30
  
  # Error handling
  max_retry_attempts: 3
  retry_backoff_multiplier: 2
  dead_letter_queue_enabled: true
  
  # Performance tuning
  concurrent_source_fetches: 4
  max_memory_per_source_mb: 512
  connection_pool_size: 10
  
  # Monitoring
  health_check_interval_minutes: 5
  metrics_collection_enabled: true
  alerting_enabled: true

# Data Quality Defaults
quality_defaults:
  completeness_threshold: 0.95
  freshness_threshold_hours: 4
  duplicate_threshold: 0.02
  outlier_detection_enabled: true
  schema_validation_enabled: true

# Federal Compliance Defaults
compliance_defaults:
  audit_logging_enabled: true
  data_classification_required: true
  encryption_at_rest: true
  retention_policy_enforced: true
  access_logging_enabled: true