# Emergency Management Data Sources Configuration
# Modular configuration for adding new data sources

data_sources:
  # Federal Emergency Management Agency
  fema:
    name: "FEMA OpenFEMA API"
    description: "Federal disaster declarations and emergency data"
    enabled: true
    
    api_config:
      base_url: "https://www.fema.gov/api/open/v2"
      endpoints:
        disaster_declarations: "/DisasterDeclarationsSummaries"
        public_assistance: "/PublicAssistanceApplicants"
        individual_assistance: "/IndividualAssistancePrograms"
      
      authentication:
        type: "none"  # Public API
        rate_limit_per_hour: 1000
      
      request_config:
        timeout_seconds: 30
        retry_attempts: 3
        retry_delay_seconds: 5
        batch_size: 5000
    
    data_mapping:
      disaster_number: "disasterNumber"
      state: "state"
      declaration_date: "declarationDate"
      incident_type: "incidentType"
      title: "title"
    
    quality_rules:
      required_fields: ["disasterNumber", "state", "declarationDate"]
      date_format: "%Y-%m-%dT%H:%M:%S.%fZ"
      state_code_validation: true

  # National Oceanic and Atmospheric Administration
  noaa:
    name: "NOAA Weather API"
    description: "Weather alerts, forecasts, and climate data"
    enabled: true
    
    api_config:
      base_url: "https://api.weather.gov"
      endpoints:
        active_alerts: "/alerts/active"
        forecast: "/gridpoints/{office}/{gridX},{gridY}/forecast"
        stations: "/stations"
      
      authentication:
        type: "none"  # Public API
        rate_limit_per_hour: 5000
        user_agent: "EmergencyManagement/1.0 (contact@emergency-data.gov)"
      
      request_config:
        timeout_seconds: 30
        retry_attempts: 3
        retry_delay_seconds: 2
        batch_size: 1000
    
    data_mapping:
      alert_id: "properties.id"
      event_type: "properties.event"
      severity: "properties.severity"
      urgency: "properties.urgency"
      headline: "properties.headline"
      effective: "properties.effective"
      expires: "properties.expires"
    
    quality_rules:
      required_fields: ["id", "event", "severity"]
      datetime_format: "ISO8601"
      severity_values: ["Minor", "Moderate", "Severe", "Extreme"]

  # Colorado Agricultural Meteorological Network
  coagmet:
    name: "CoAgMet Weather Stations"
    description: "Agricultural weather monitoring for Colorado"
    enabled: true
    
    api_config:
      base_url: "https://coagmet.colostate.edu/data_access/web_service"
      endpoints:
        stations: "/get_stations.php"
        station_data: "/get_data.php"
      
      authentication:
        type: "api_key"
        api_key_env: "COAGMET_API_KEY"
        rate_limit_per_hour: 2000
      
      request_config:
        timeout_seconds: 45
        retry_attempts: 3
        retry_delay_seconds: 3
        batch_size: 500
    
    data_mapping:
      station_id: "station_id"
      timestamp: "timestamp"
      temperature: "temperature"
      humidity: "humidity"
      precipitation: "precipitation"
      wind_speed: "wind_speed"
    
    quality_rules:
      required_fields: ["station_id", "timestamp"]
      temperature_range: [-50, 120]  # Fahrenheit
      humidity_range: [0, 100]
      precipitation_max: 50  # inches per day

  # United States Department of Agriculture
  usda:
    name: "USDA NASS QuickStats"
    description: "Agricultural statistics and crop data"
    enabled: true
    
    api_config:
      base_url: "https://quickstats.nass.usda.gov/api"
      endpoints:
        quickstats: "/api_GET/"
        crop_progress: "/get_progress/"
      
      authentication:
        type: "api_key"
        api_key_env: "USDA_API_KEY"
        rate_limit_per_hour: 500
      
      request_config:
        timeout_seconds: 60
        retry_attempts: 3
        retry_delay_seconds: 10
        batch_size: 1000
    
    data_mapping:
      year: "year"
      state_fips: "state_fips_code"
      commodity: "commodity_desc"
      data_item: "data_item"
      value: "Value"
    
    quality_rules:
      required_fields: ["year", "state_fips_code", "commodity_desc"]
      year_range: [2000, 2030]
      numeric_validation: true

# Custom data source template for easy extension
custom_source_template:
  name: "Custom Data Source"
  description: "Template for adding new emergency data sources"
  enabled: false
  
  api_config:
    base_url: ""
    endpoints: {}
    authentication:
      type: "none"  # Options: none, api_key, oauth, basic
      rate_limit_per_hour: 1000
    
    request_config:
      timeout_seconds: 30
      retry_attempts: 3
      retry_delay_seconds: 5
      batch_size: 1000
  
  data_mapping: {}
  
  quality_rules:
    required_fields: []
    custom_validation_rules: []

# Global configuration
global_config:
  # Default settings applied to all sources
  defaults:
    max_concurrent_requests: 5
    request_timeout: 30
    retry_backoff_factor: 2
    enable_caching: true
    cache_ttl_seconds: 300
  
  # Data classification
  classification:
    default_level: "PUBLIC"
    sensitive_fields: []
    pii_detection: true
  
  # Federal compliance
  compliance:
    audit_logging: true
    data_retention_days: 2555  # 7 years
    encryption_required: true
    access_logging: true
  
  # Error handling
  error_handling:
    max_error_rate: 10  # percent
    circuit_breaker_threshold: 5
    circuit_breaker_timeout: 300
    dead_letter_queue: true
  
  # Monitoring
  monitoring:
    health_check_interval: 300  # seconds
    metrics_collection: true
    alert_on_failure: true
    performance_tracking: true

# Environment-specific overrides
environments:
  development:
    global_config:
      defaults:
        max_concurrent_requests: 2
        enable_caching: false
      monitoring:
        health_check_interval: 60
  
  production:
    global_config:
      defaults:
        max_concurrent_requests: 10
        request_timeout: 60
      error_handling:
        max_error_rate: 5
        circuit_breaker_threshold: 3
      monitoring:
        health_check_interval: 60
        alert_on_failure: true

# Data source grouping for job scheduling
source_groups:
  real_time:
    sources: ["noaa"]
    schedule: "*/5 * * * *"  # Every 5 minutes
    priority: "HIGH"
  
  frequent:
    sources: ["fema", "coagmet"]
    schedule: "0 */1 * * *"  # Every hour
    priority: "MEDIUM"
  
  batch:
    sources: ["usda"]
    schedule: "0 6 * * *"  # Daily at 6 AM
    priority: "LOW"